; Load igbinary extension
extension=igbinary.so

; Use igbinary as session serializer
session.serialize_handler=igbinary

; Enable or disable compacting of duplicate strings
; The default is On.
igbinary.compact_strings=On

# Activate the xhprof extension we installed.
extension=xhprof.so

# Set XDebug log level to 0 to avoid CLI warning messages.
xdebug.log_level=0
