#!/bin/sh

# This file is managed by dropfort/dropfort_build.
# Modifications to this file will be overwritten by default.

[ -n "$CI" ] && exit 0

echo committing as $(git config user.name)
npx lint-staged
